Router.configure({
	layoutTemplate:'layout'
});
Router.route('/',{name:'page1'});
Router.route('/ballz',{
	name:'famoBallz',
	waitOn:function(){Meteor.subscribe('peeps');}
});
Router.route('/flippy',{name:'flippy'});
Router.route('/flipper',{name:'flipper'});